# FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel
FROM nvcr.io/nvidia/pytorch:22.09-py3

RUN pip install pydicom
RUN pip install pynrrd
RUN pip install h5py
RUN pip install matplotlib
RUN pip install scikit-image
RUN pip install jupyterlab
RUN pip install natsort
RUN pip install gudhi

RUN apt update && apt -y install git
